apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera
  namespace: a1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera
  template:
    metadata:
      labels:
        app: camera
    spec:
      containers:
        - name: camera
          image: ccuni/camera-service-2025w
          ports:
            - containerPort: 80
          env:
            - name: SECTION_ID
              value: "1"
            - name: POSITION
              value: "entry"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: camera
  namespace: a1
spec:
  selector:
    app: camera
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
