apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-analysis
  namespace: a1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-analysis
  template:
    metadata:
      labels:
        app: image-analysis
    spec:
      containers:
        - name: image-analysis
          image: ccuni/image-analysis-service-2025w
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: image-analysis
  namespace: a1
spec:
  selector:
    app: image-analysis
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
